name: Application Test Before Push/Merge
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: docker/build-push-action@v2
        with:
          tags: cryptoracle
          push: false
      - uses: addnab/docker-run-action@v3
        with:
          image: cryptoracle
          run: echo "hello world"
      - run: npm install
      - run: npm test
