name: Application Test Before Push
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - run: npm install
      - run: npm start
