name: Application Test Before Push/Merge
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - run: npm install
      - run: npm test
  buildandpushdocker:
      needs: tests
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./app
      steps:        
        -
          name: Checkout
          uses: actions/checkout@v2
        -
          name: Set up QEMU
          uses: docker/setup-qemu-action@v1
        -
          name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1
        -
          name: Login to DockerHub
          uses: docker/login-action@v1 
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        
        - uses: docker/build-push-action@v2
          with:
            tags: cryptoracle
            push: true
       
        - uses: addnab/docker-run-action@v3
          with:
              image: cryptoracle
              run: echo "hello world"
